-- MySQL Script generated by MySQL Workbench
-- Tue Aug 28 10:59:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gocip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gocip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gocip` DEFAULT CHARACTER SET utf8 ;
USE `gocip` ;

-- -----------------------------------------------------
-- Table `gocip`.`annuaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocip`.`annuaire` (
  `idannuaire` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `telephone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idannuaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocip`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocip`.`type` (
  `idtype` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocip`.`societes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocip`.`societes` (
  `idsocietes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `pays` VARCHAR(45) NOT NULL,
  `telephone` INT NOT NULL,
  `num_tva` INT NOT NULL,
  `type_idtype` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idsocietes`),
  INDEX `fk_societes_type1_idx` (`type_idtype` ASC),
  CONSTRAINT `fk_societes_type1`
    FOREIGN KEY (`type_idtype`)
    REFERENCES `gocip`.`type` (`idtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocip`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocip`.`facture` (
  `idfacture` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `date_facture` DATE NOT NULL,
  `date_prestation` DATE NOT NULL,
  `societes_idsocietes` INT UNSIGNED NOT NULL,
  `annuaire_idannuaire` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idfacture`),
  INDEX `fk_facture_societes1_idx` (`societes_idsocietes` ASC),
  INDEX `fk_facture_annuaire1_idx` (`annuaire_idannuaire` ASC),
  CONSTRAINT `fk_facture_societes1`
    FOREIGN KEY (`societes_idsocietes`)
    REFERENCES `gocip`.`societes` (`idsocietes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_annuaire1`
    FOREIGN KEY (`annuaire_idannuaire`)
    REFERENCES `gocip`.`annuaire` (`idannuaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gocip`.`annuaire_has_societes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gocip`.`annuaire_has_societes` (
  `annuaire_idannuaire` INT UNSIGNED NOT NULL,
  `societes_idsocietes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`annuaire_idannuaire`, `societes_idsocietes`),
  INDEX `fk_annuaire_has_societes_societes1_idx` (`societes_idsocietes` ASC),
  INDEX `fk_annuaire_has_societes_annuaire1_idx` (`annuaire_idannuaire` ASC),
  CONSTRAINT `fk_annuaire_has_societes_annuaire1`
    FOREIGN KEY (`annuaire_idannuaire`)
    REFERENCES `gocip`.`annuaire` (`idannuaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annuaire_has_societes_societes1`
    FOREIGN KEY (`societes_idsocietes`)
    REFERENCES `gocip`.`societes` (`idsocietes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
